apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sandhyalb1
  name: sandhyalb1 # name of internal LB 
spec:
  ports:
  - name: 7645-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector: # the way internal lb will be finding pod IP in svc discovery DB 
    #app: ashulb1
    x1: sandhyapod1 # label of pods 
  type: ClusterIP # type of service 
status:
  loadBalancer: {}