apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sandhya-app-deploy
  name: sandhyalb2
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: sandhya-app-deploy
  type: ClusterIP
status:
  loadBalancer: {}
